### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by VoVanToan26** [VoVanToan26/git-flow#6]
REQUEST 
--

- [ ] Tạo task lisT
- [ ] Commit code

TODO
--
- [ ] Tạo file README.md
- [ ] Config git account
